export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const DECREMENT_COUNTER_ASYNC = 'DECREMENT_COUNTER_ASYNC';

export const LOAD_DATA_REQUESTED = 'LOAD_DATA_REQUESTED';
export const LOAD_DATA_STARTED = 'LOAD_DATA_STARTED';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR';
